# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: chsxf.dev
email: chsxf.pro@gmail.com
tagline: Discover everything about my personal works as a game dev, mostly on Apple platforms
intro: >- # this means to ignore newlines until "baseurl:"
  Senior Unity Developer at <a href="https://altshift.fr">Alt Shift</a> by day, hobbyist game dev the rest of the time, this devlog is all about my personal works.
  <br />
  Apple user for more than 15 years. Expect most projects here to be Apple-compatible only.
  <br /><br />
  <em>If you're looking for info about Alt Shift's commercial projects, check my <a href="https://chsxf.medium.com">Medium</a> page, or Alt Shift social accounts.</em>
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://chsxf.dev" # the base hostname & protocol for your site, e.g. http://example.com
author:
  name: Christophe SAUVEUR
  twitter: chsxf

twitter:
  username: chsxf

socials:
  - name: GitHub
    url: https://github.com/chsxf
    img: github.png
  - name: itch.io
    url: https://chsxf.itch.io/
    img: itch.png
  - name: Mastodon
    url: https://mastodon.gamedev.place/@chsxf
    img: mastodon.png
  - name: X
    url: https://x.com/chsxf
    img: x.png
  - name: Medium
    url: https://chsxf.medium.com
    img: medium.png
  - name: LinkedIn
    url: https://www.linkedin.com/in/christophesauveur/
    img: linkedin.png
  - name: RSS Feed
    url: /feed.xml
    img: rss.png

logo: https://avatars.githubusercontent.com/u/3322862

# Build settings
#theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

github:
  is_project_page: false
  is_user_page: true
  owner_username: chsxf
  owner_url: https://github.com/chsxf
  show_user_stats: true
  show_langs_stats: true

google_analytics: G-95625D8V1Q

paginate: 5
paginate_path: "/page:num"

excerpt_separator: <!--more-->
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
